package com.learning.student;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

class StudentTest {

    @Test
    void testLombokGettersAndSetters() {
        Student s = new Student();
        s.setId(101);
        s.setName("Aum");

        // Verify getters (automatically generated by Lombok @Data)
        assertEquals(101, s.getId());
        assertEquals("Aum", s.getName());
    }

    @Test
    void testLombokBuilder() {
        // Verify Builder pattern (automatically generated by Lombok @Builder)
        Student s = Student.builder()
                .id(102)
                .name("Aum")
                .build();

        assertNotNull(s);
        assertEquals(102, s.getId());
        assertEquals("Aum", s.getName());
    }

    @Test
    void testLombokToStringEqualsHashCode() {
        Student s1 = new Student(103, "Aum");
        Student s2 = new Student(103, "Aum");

        // Verify equals and hashCode (automatically generated by Lombok @Data)
        assertEquals(s1, s2);
        assertEquals(s1.hashCode(), s2.hashCode());

        // Verify toString contains fields
        assertTrue(s1.toString().contains("id=103"));
        assertTrue(s1.toString().contains("name=Aum"));
    }
}
